version: 0.0
os: linux
files:
  - source: /
    destination: /var/api/
hooks:
  BeforeInstall:
    - location: scripts/install-dependencies.sh
      runas: root
      timeout: 600
  ApplicationStart:
    - location: scripts/application-start.sh
      runas: root
      timeout: 300