version: 0.0
os: linux
files:
  - source: /
    destination: /var/api/
hooks:
  BeforeInstall:
    - location: scripts/install-dependencies.sh
      runas: ubuntu
      timeout: 300
  ApplicationStart:
    - location: scripts/application-start.sh
      runas: ubuntu
      timeout: 60
  ApplicationStop:
    - location: scripts/application-stop.sh
      runas: ubuntu
      timeout: 60