version: 0.2

phases:
  install:
    commands:
      - echo Entering install phase...
  pre_build:
    commands:
      - echo Entering pre build phase...
  build:
    commands:
      - echo Entering build phase...
      - npm install
  post_build:
    commands:
      - echo Entered the post_build phase...
      - npm run build
artifacts:
  files:
    - target/*